quarkus:
  http:
    port: 9081
  datasource:
    db-kind: h2
    username: sa
    password: password
    jdbc:
      url: jdbc:h2:mem:user_v1
      max-size: 8
      min-size: 2
  hibernate-orm:
    database:
      generation: drop-and-create


### Kafka configuration
kafka:
  bootstrap:
    servers: localhost:9092


####Channels configurations under kafka
mp:
  messaging:
    incoming:
      notification:
        connector: smallrye-kafka
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer