quarkus:
  http:
    port: 9084
  datasource:
    db-kind: h2
    username: sa
    password: password
    jdbc:
      url: jdbc:h2:mem:order_v1
      max-size: 8
      min-size: 2
  hibernate-orm:
    database:
      generation: drop-and-create

com:
  srp:
    order:
      restclient:
        InventoryClient/mp-rest/url: http://localhost:9083/


### Kafka configuration
kafka:
  bootstrap:
    servers: localhost:9092


####Channels configurations under kafka
mp:
  messaging:
    outgoing:
      notification:
        connector: smallrye-kafka
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer