quarkus:
  http:
    port: 9083
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    reactive:
      url: postgresql://localhost:5432/stock_v1
  hibernate-orm:
    database:
      generation: drop-and-create
      log:
        sql: true